insert into category(id, name, value) values (1, "Excited", 5);
insert into category(id, name, value) values (2, "Want", 3);
insert into category(id, name, value) values (3, "Like", 2);
insert into category(id, name, value) values (4, "lolnope", -4);

insert into gaming_group(name) values ('Test Gaming Group ');
insert into gaming_group(name) values ('Some Group name ');

insert into gaming_group_members(groupid, gamerid) values (1, 1);
insert into gaming_group_members(groupid, gamerid) values (1, 2);
insert into gaming_group_members(groupid, gamerid) values (2, 1);

insert into game(name) values ("Great Western Trail");
insert into game(name) values ("Feast for Odin");
insert into game(name) values ("CO2");
insert into game(name) values ("T’zolkin");
insert into game(name) values ("Brass:Birmingham");
insert into game(name) values ("Teotihuacan");
insert into game(name) values ("Treasure Island");
insert into game(name) values ("Scythe");
insert into game(name) values ("Gears of War");
insert into game(name) values ("Black Orchestra");
insert into game(name) values ("Sagrada");
insert into game(name) values ("Cyclades");
insert into game(name) values ("Inis");
insert into game(name) values ("Forbidden stars");
insert into game(name) values ("Root");
insert into game(name) values ("T'zolkin");
insert into game(name) values ("Galaxy Defenders");
insert into game(name) values ("Arkham Horror 3rd");
insert into game(name) values ("Descent");
insert into game(name) values ("Euphoria");
insert into game(name) values ("Nemesis");
insert into game(name) values ("Roll Player");
insert into game(name) values ("Waste Knights");
insert into game(name) values ("The Others");
insert into game(name) values ("Rising Sun");
insert into game(name) values ("Blood Rage");
insert into game(name) values ("Viticulture");
insert into game(name) values ("Champions of Midgard");
insert into game(name) values ("KDM");
insert into game(name) values ("Terraforming Mars");
insert into game(name) values ("Wildlands");
insert into game(name) values ("Gaia Project");
insert into game(name) values ("Raiders");
insert into game(name) values ("Shadows Over Normandie");
insert into game(name) values ("Sword Sorcery");
insert into game(name) values ("Western Legends");
insert into game(name) values ("Xia");
insert into game(name) values ("Wingspan");

insert into gamer(name, active) values ("Steve", 0);
insert into gamer(name, active) values ("Jerkwood", 1);
insert into gamer(name, active) values ("Ryan", 1);
insert into gamer(name, active) values ("Sam", 0);
insert into gamer(name, active) values ("Mark", 0);


insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	7  ,1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	8  ,1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	9  ,1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	10,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	11,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	12,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	28,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	15,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	16,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	14,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	20,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	21,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	29,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	30,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	18,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	19,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	23,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	31,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	17,	4);
insert into gamer_game_category(gamerid, gameid, categoryid) values(4,	40,	4);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	13,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	8 ,1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	14,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	15,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	16,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	17,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	18,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	19,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	7	,1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	20,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	11,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	21,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	10,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	23,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	12,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	29,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	9	,2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	30,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	31,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	32,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	33,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	34,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	35,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	36,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	40,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	28,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(1,	41,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	20,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	14,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	18,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	11,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	24,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	13,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	12,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	25,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	26,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	27,	1);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	15,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	36,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	16,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	17,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	22,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	37,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	38,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	7	,2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	9	,2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	21,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	39,	2);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	28,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	31,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	8	,3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	42,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	43,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	44,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	19,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	32,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	40,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	33,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	34,	3);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	30,	4);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	23,	4);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	41,	4);
insert into gamer_game_category(gamerid, gameid, categoryid) values(2,	35,	4);





